name: ffitnessconceptsmember
description: A new Flutter application for Fitness Concepts Members.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  intl: ^0.16.0
  qr_flutter: ^3.0.1
  image_picker: ^0.6.3+4
  path_provider: ^1.3.0
  fluttertoast: ^3.1.3
  fl_chart: ^0.4.1
  sqflite: ^1.1.5
  camera: ^0.5.7+3
  dio: ^3.0.8
  path: ^1.6.4

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/logo.jpg"
  image_path_android: "assets/logo.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


  uses-material-design: true
  fonts:
    - family:  MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
  assets:
    - assets/
